module.exports = {
    Login : "Login",
    Signup: "Signup",
    AccountSettings: "Account Settings",
    ListArtifacts: "All Artifacts",
    ListWeapons: "All Weapons",
    ListCharacters: "All Characters",
    ListTeams: "All Teams ",
    SingleArtifact: "SingleArtifact",
    SingleWeapon: "SingleWeapon",
    SingleCharacter: "SingleCharacter",
    SingleTeam: "SingleTeam",
    ChooseArtifact: "ChooseArtifact",
    ChooseWeapon: "ChooseWeapon",
    ChooseCharacter: "ChooseCharacter",
    ChooseProfilePicture: "ChooseProfilePicture",

    Drawer: "Drawer",
    Homepage: "Home",
    Characters: "Characters",
    Artifacts: "Artifacts",
    Weapons: "Weapons",
    Teams: "Teams",
    Settings: "Settings"
};
